## POSTTEST 4

Import library pandas,numpy, sklearn dan membaca data csv

In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
data = pd.read_csv('player_stats.csv')

,Unnamed: 0,match_id,game_id,team,score_team,opponent,score_opp,win_lose,map,map_pick,...,rating,acs,kill,death,assist,kast%,adr,hs%,fk,fd
1050,1050,53713,119677,ZETA,13,TS,15,opponent win,Haven,opponent pick,...,,,25,20,16,,,,,
1051,1051,53713,119677,ZETA,13,TS,15,opponent win,Haven,opponent pick,...,,,16,20,9,,,,,
1052,1052,53713,119677,ZETA,13,TS,15,opponent win,Haven,opponent pick,...,,,17,23,8,,,,,
1053,1053,53713,119677,ZETA,13,TS,15,opponent win,Haven,opponent pick,...,,,17,20,10,,,,,
1054,1054,53713,119677,ZETA,13,TS,15,opponent win,Haven,opponent pick,...,,,20,22,2,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6225,6225,61192,137642,EG,13,PRX,10,team win,Lotus,team pick,...,1.43,244,23,13,10,83%,162,46%,0,1
6226,6226,61192,137642,EG,13,PRX,10,team win,Lotus,team pick,...,1.26,338,26,18,5,78%,225,18%,7,3
6227,6227,61192,137642,EG,13,PRX,10,team win,Lotus,team pick,...,1.09,198,16,16,1,65%,131,36%,2,2
6228,6228,61192,137642,EG,13,PRX,10,team win,Lotus,team pick,...,0.86,180,13,17,15,74%,108,29%,2,3
6229,6229,61192,137642,EG,13,PRX,10,team win,Lotus,team pick,...,0.86,118,9,13,8,74%,82,30%,1,2

memcopy datanya dan merubah kolom acs yg object menjadi integer

In [12]:
data_copy = data.copy()
data_copy['acs'] = pd.to_numeric(data_copy['acs'], errors='coerce', downcast='integer')

membuat dataset menjadi training set dan testing set dengan proporsi 70:30

di training set dan testing set untuk memprediksi memang kalahnya suatu tim

In [13]:
X = data_copy.drop(columns=['win_lose'])
y = data_copy['win_lose']
proporsi_testing = 0.3

X_training, X_testing, y_training, y_testing = train_test_split(X, y, test_size=proporsi_testing, random_state=42)
X_training.head()

,Unnamed: 0,match_id,game_id,team,score_team,opponent,score_opp,map,map_pick,player_id,...,rating,acs,kill,death,assist,kast%,adr,hs%,fk,fd
1034,1034,53702,119644,RRQ,9,PRX,13,Bind,team pick,7403,...,0.76,171.0,12,18,5,59%,119,23%,2,5
2957,2957,53457,118959,SEN,12,LEV,14,Split,team pick,9,...,1.01,199.0,18,18,5,65%,136,28%,1,3
5290,5290,59976,134572,SEN,4,LEV,13,Split,team pick,4004,...,0.89,252.0,13,15,5,76%,171,18%,3,4
5286,5286,59976,134571,LEV,13,SEN,8,Fracture,team pick,7603,...,1.29,255.0,19,13,8,81%,163,29%,2,1
6100,6100,61191,137638,PRX,15,EG,13,Pearl,opponent pick,9800,...,1.39,235.0,23,14,14,75%,170,33%,0,3

 normalisasi data pada attribute acs menggunakan Min Max scaler

In [14]:
from sklearn.preprocessing import MinMaxScaler

kolom_normalisasi = ['score_team']


scaler = MinMaxScaler()

data_copy[kolom_normalisasi] = scaler.fit_transform(data_copy[kolom_normalisasi])
data_copy

,Unnamed: 0,match_id,game_id,team,score_team,opponent,score_opp,win_lose,map,map_pick,...,rating,acs,kill,death,assist,kast%,adr,hs%,fk,fd
0,0,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,1.19,239.0,15,11,6,72%,146,16%,1,0
1,1,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,0.84,234.0,15,14,6,61%,145,32%,1,4
2,2,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,0.68,173.0,10,15,2,67%,123,18%,4,2
3,3,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,0.63,142.0,8,15,4,83%,92,29%,3,2
4,4,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,0.57,114.0,7,16,8,61%,63,13%,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6225,6225,61192,137642,EG,0.619048,PRX,10,team win,Lotus,team pick,...,1.43,244.0,23,13,10,83%,162,46%,0,1
6226,6226,61192,137642,EG,0.619048,PRX,10,team win,Lotus,team pick,...,1.26,338.0,26,18,5,78%,225,18%,7,3
6227,6227,61192,137642,EG,0.619048,PRX,10,team win,Lotus,team pick,...,1.09,198.0,16,16,1,65%,131,36%,2,2
6228,6228,61192,137642,EG,0.619048,PRX,10,team win,Lotus,team pick,...,0.86,180.0,13,17,15,74%,108,29%,2,3
6229,6229,61192,137642,EG,0.619048,PRX,10,team win,Lotus,team pick,...,0.86,118.0,9,13,8,74%,82,30%,1,2

Melakukan  standarisasi pada kolom acs,kill,death,assist menggunakan sklearn

In [15]:
from sklearn.preprocessing import StandardScaler
data_copy['acs'] = pd.to_numeric(data['acs'], errors='coerce', downcast='integer')
kolom_standarisasi = [ 'acs', 'kill', 'death', 'assist']
scaler = StandardScaler()
data_copy[kolom_standarisasi] = scaler.fit_transform(data_copy[kolom_standarisasi])

Lakukan Data cleaning pada data dengan nilai null dan Ganti nilai null sesuai ketentuan

Menampilkan data yg ada nullnya

In [16]:
baris_dengan_null = data_copy[data_copy.isnull().any(axis=1)]
baris_dengan_null

,Unnamed: 0,match_id,game_id,team,score_team,opponent,score_opp,win_lose,map,map_pick,...,rating,acs,kill,death,assist,kast%,adr,hs%,fk,fd
1050,1050,53713,119677,ZETA,0.619048,TS,15,opponent win,Haven,opponent pick,...,,NaN,1.915325,1.412364,2.325836,,,,,
1051,1051,53713,119677,ZETA,0.619048,TS,15,opponent win,Haven,opponent pick,...,,NaN,0.223255,1.412364,0.594274,,,,,
1052,1052,53713,119677,ZETA,0.619048,TS,15,opponent win,Haven,opponent pick,...,,NaN,0.411263,2.230193,0.346908,,,,,
1053,1053,53713,119677,ZETA,0.619048,TS,15,opponent win,Haven,opponent pick,...,,NaN,0.411263,1.412364,0.841640,,,,,
1054,1054,53713,119677,ZETA,0.619048,TS,15,opponent win,Haven,opponent pick,...,,NaN,0.975286,1.957583,-1.137288,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5725,5725,61036,137389,NRG,0.714286,ZETA,13,team win,Bind,opponent pick,...,,NaN,0.975286,0.594534,0.841640,,,,,
5726,5726,61036,137389,NRG,0.714286,ZETA,13,team win,Bind,opponent pick,...,,NaN,2.291341,0.867144,2.325836,,,,,
5727,5727,61036,137389,NRG,0.714286,ZETA,13,team win,Bind,opponent pick,...,,NaN,1.163294,2.230193,0.346908,,,,,
5728,5728,61036,137389,NRG,0.714286,ZETA,13,team win,Bind,opponent pick,...,,NaN,-0.904791,1.684973,1.831104,,,,,
5729,5729,61036,137389,NRG,0.714286,ZETA,13,team win,Bind,opponent pick,...,,NaN,1.163294,0.321925,1.336372,,,,,

melakukan pergantian data null sesuai tipe datanya

In [17]:
nilai_null = data_copy.isnull().sum()
kolom_dengan_data_null = data_copy.columns[data_copy.any()].tolist()
for kolom in kolom_dengan_data_null:
    if nilai_null[kolom] > 0:
        tipe_data_kolom = data_copy[kolom].dtype
        print(tipe_data_kolom)
        if tipe_data_kolom == 'int64':
            median = data_copy[kolom].median()
            data_copy[kolom].fillna(median, inplace=True)
        elif tipe_data_kolom == 'float64':
            mean = data_copy[kolom].mean()
            data_copy[kolom].fillna(mean, inplace=True)
        elif tipe_data_kolom == 'object':
            modus = data_copy[kolom].mode()[0]
            data_copy[kolom].fillna(modus, inplace=True)

float64

Menampilkan lagi data yg sudah diubah kalo kosong berarti datanya tidak ada

In [18]:
baris_dengan_null = data_copy[data_copy.isnull().any(axis=1)]
baris_dengan_null

Empty DataFrame
Columns: [Unnamed: 0, match_id, game_id, team, score_team, opponent, score_opp, win_lose, map, map_pick, player_id, player, agent, rating, acs, kill, death, assist, kast%, adr, hs%, fk, fd]
Index: []

[0 rows x 23 columns]

Melakukan Data cleaning pada data dengan nilai duplikat

Mengechek data ada yg duplikat atau tidak

In [19]:
data_duplikat = data_copy[data_copy.duplicated(keep=False)]
data_duplikat

Empty DataFrame
Columns: [Unnamed: 0, match_id, game_id, team, score_team, opponent, score_opp, win_lose, map, map_pick, player_id, player, agent, rating, acs, kill, death, assist, kast%, adr, hs%, fk, fd]
Index: []

[0 rows x 23 columns]

Karena kosong buat data duplikatnya contoh tambah 10 data duplikat

In [21]:
jumlah_duplikat = 10
buat_duplikat = pd.concat([data_copy] * jumlah_duplikat, ignore_index=True)

melihat data yg sudah diduplikat

In [22]:
data_duplikat = buat_duplikat[buat_duplikat.duplicated(keep=False)]
data_duplikat

,Unnamed: 0,match_id,game_id,team,score_team,opponent,score_opp,win_lose,map,map_pick,...,rating,acs,kill,death,assist,kast%,adr,hs%,fk,fd
0,0,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,1.19,0.725692,0.035248,-1.041124,-0.147824,72%,146,16%,1,0
1,1,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,0.84,0.637389,0.035248,-0.223295,-0.147824,61%,145,32%,1,4
2,2,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,0.68,-0.439906,-0.904791,0.049315,-1.137288,67%,123,18%,4,2
3,3,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,0.63,-0.987384,-1.280807,0.049315,-0.642556,83%,92,29%,3,2
4,4,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,0.57,-1.481880,-1.468814,0.321925,0.346908,61%,63,13%,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62295,6225,61192,137642,EG,0.619048,PRX,10,team win,Lotus,team pick,...,1.43,0.813995,1.539310,-0.495905,0.841640,83%,162,46%,0,1
62296,6226,61192,137642,EG,0.619048,PRX,10,team win,Lotus,team pick,...,1.26,2.474089,2.103333,0.867144,-0.395190,78%,225,18%,7,3
62297,6227,61192,137642,EG,0.619048,PRX,10,team win,Lotus,team pick,...,1.09,0.001608,0.223255,0.321925,-1.384654,65%,131,36%,2,2
62298,6228,61192,137642,EG,0.619048,PRX,10,team win,Lotus,team pick,...,0.86,-0.316282,-0.340768,0.594534,2.078470,74%,108,29%,2,3
62299,6229,61192,137642,EG,0.619048,PRX,10,team win,Lotus,team pick,...,0.86,-1.411238,-1.092799,-0.495905,0.346908,74%,82,30%,1,2

lalu bersihkan data yg sudah terduplikat

In [25]:
bersihkan_data = data_duplikat.drop_duplicates()
bersihkan_data

,Unnamed: 0,match_id,game_id,team,score_team,opponent,score_opp,win_lose,map,map_pick,...,rating,acs,kill,death,assist,kast%,adr,hs%,fk,fd
0,0,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,1.19,0.725692,0.035248,-1.041124,-0.147824,72%,146,16%,1,0
1,1,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,0.84,0.637389,0.035248,-0.223295,-0.147824,61%,145,32%,1,4
2,2,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,0.68,-0.439906,-0.904791,0.049315,-1.137288,67%,123,18%,4,2
3,3,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,0.63,-0.987384,-1.280807,0.049315,-0.642556,83%,92,29%,3,2
4,4,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,0.57,-1.481880,-1.468814,0.321925,0.346908,61%,63,13%,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6225,6225,61192,137642,EG,0.619048,PRX,10,team win,Lotus,team pick,...,1.43,0.813995,1.539310,-0.495905,0.841640,83%,162,46%,0,1
6226,6226,61192,137642,EG,0.619048,PRX,10,team win,Lotus,team pick,...,1.26,2.474089,2.103333,0.867144,-0.395190,78%,225,18%,7,3
6227,6227,61192,137642,EG,0.619048,PRX,10,team win,Lotus,team pick,...,1.09,0.001608,0.223255,0.321925,-1.384654,65%,131,36%,2,2
6228,6228,61192,137642,EG,0.619048,PRX,10,team win,Lotus,team pick,...,0.86,-0.316282,-0.340768,0.594534,2.078470,74%,108,29%,2,3
6229,6229,61192,137642,EG,0.619048,PRX,10,team win,Lotus,team pick,...,0.86,-1.411238,-1.092799,-0.495905,0.346908,74%,82,30%,1,2

Ganti tipe data salah satu attribute angka

In [26]:
data_copy['acs'] = data_copy['kill'].astype(float)

melakukan one hot encoding

di dalam kodingan tersebut mengencoding data di kolom win_lose lalu menambahkan kolom baru kalo dengan isi kalo opponent win = 1 sedangkan team win = 0

In [27]:
from sklearn.preprocessing import OneHotEncoder
OneHotEncoder = OneHotEncoder(sparse_output=False)
Win_lose_Encoding = OneHotEncoder.fit_transform(data_copy[["win_lose"]])
Win_lose_Encoding = pd.DataFrame(Win_lose_Encoding)
data_copy['opponent win'] = Win_lose_Encoding[0]
data_copy['team win'] = Win_lose_Encoding[1]
data_copy.head()

,Unnamed: 0,match_id,game_id,team,score_team,opponent,score_opp,win_lose,map,map_pick,...,kill,death,assist,kast%,adr,hs%,fk,fd,opponent win,team win
0,0,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,0.035248,-1.041124,-0.147824,72%,146,16%,1,0,1.0,0.0
1,1,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,0.035248,-0.223295,-0.147824,61%,145,32%,1,4,1.0,0.0
2,2,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,-0.904791,0.049315,-1.137288,67%,123,18%,4,2,1.0,0.0
3,3,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,-1.280807,0.049315,-0.642556,83%,92,29%,3,2,1.0,0.0
4,4,53658,119512,ZETA,0.238095,DRX,13,opponent win,Ascent,opponent pick,...,-1.468814,0.321925,0.346908,61%,63,13%,0,1,1.0,0.0